### ISSUE TITLE
Don't define global method "assert"

### ISSUE THREAD

**Issue by TSMMark** [pdfcrowd/pdfcrowd-ruby#5]
https://github.com/pdfcrowd/pdfcrowd-ruby/blob/f11d34a1551e75984d95257de0e10eec0daeacfb/lib/pdfcrowd.rb#L403-L405

conflicts with testing libraries like minitest, cutest, etc.

Should be just as easy to `def assert` on a pdfcrowd module instead.

# Example of what can go wrong

```
ArgumentError: wrong number of arguments (given 2, expected 0)
    /usr/local/bundle/ruby/3.0.0/gems/pdfcrowd-4.4.2/lib/pdfcrowd.rb:403:in `assert'
    /usr/local/bundle/ruby/3.0.0/gems/cutest-1.2.3/lib/cutest.rb:159:in `assert_equal'
```

**Comment by foxmadr** [comment]
The method was renamed to avoid conflict.
